---
name: Pre-commit checks

on:
  # Do not run on push to main, as main will have lots of automated commits
  pull_request:
    branches:
      - "**"

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run Pre-commit checks
        run: pre-commit run -a --show-diff-on-failure
